spring:
  datasource:
    url: postgres://rlxqpmiopfceor:4a936cc8b28d2f9a3cf91a620356ae0a1a0ad9f0b853597eaff4d41f673359ee@ec2-52-203-118-49.compute-1.amazonaws.com:5432/d2o1sv9rutpjom
    username: rlxqpmiopfceor
    password: 4a936cc8b28d2f9a3cf91a620356ae0a1a0ad9f0b853597eaff4d41f673359ee
  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never
    include-message: always

    spring:
      mail:
        properties:
          mail:
            smtp:
              starttls:
                enable: 'true'
              auth: 'true'
        host: smtp.gmail.com
        username: codetest.shazzar@gmail.com
        password: phfnxnwncvzfedqq
        port: '587'

  logging:
    pattern:
      console:
    level: 'false'
    root: OFF
