spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/voteMe?useSSL=false
    username: shazzar
    password: Las-jefa5
  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never
    include-message: always

    spring:
      mail:
        properties:
          mail:
            smtp:
              starttls:
                enable: 'true'
              auth: 'true'
        host: smtp.gmail.com
        username: codetest.shazzar@gmail.com
        password: phfnxnwncvzfedqq
        port: '587'

  logging:
    pattern:
      console:
    level: 'false'
    root: OFF
